### ISSUE TITLE
Issue in L2 marginal loss function?

### ISSUE THREAD

**Issue by mattrafuse** [ryan112358/private-pgm#1]
At [Line 247](https://github.com/ryan112358/private-pgm/blob/master/src/mbi/inference.py#L247) of inference.py, you're calculating the L_2 loss. Instead of exponentiating by 1/2, you multiply by it.

Am I misunderstanding the code here? Or is that a bug?

Thanks!

**Comment by ryan112358** [comment]
Hi, thanks for the comment.  We are technically optimizing the L2 squared loss, so there's no need to take square root.  We multiply by the constant 1/2 in the loss term to avoid the need for a 2 in the gradient term.
