### ISSUE TITLE
Scoring script from the NIST challenges

### ISSUE THREAD

**Issue by RexYuan** [ryan112358/private-pgm#15]
Could you provide the NIST scoring scripts that were used to obtain the following scores from your paper?

<img width="876" alt="Screenshot 2024-08-09 at 2 19 45 AM" src="https://github.com/user-attachments/assets/d5394b47-9e6f-4b6c-971e-f9e7f80a0241">

**Comment by ryan112358** [comment]
I copied these numbers from https://arxiv.org/pdf/1911.12704 (except for MST, which I ran new experiments for)
