### ISSUE TITLE
what the  domain size in adult_domain.json ? 

### ISSUE THREAD

**Issue by bigdaronlee163** [ryan112358/private-pgm#5]

**Comment by bigdaronlee163** [comment]
I guess the meaning of  domain size is how many the classes are ？  But when I tested this idea, I found that some did not correspond to this 。 

this is my result： 

for c in col:
    print(max(data.df[c]))
    
74
8
99
15
6
14
5
4
1
99
87
98
41
1


shape =  (85, 9, 100, 16, 7, 15, 6, 5, 2, 100, 100, 99, 42, 2)  in  adult_domain.json ? 

Another question is, will this size affect the accuracy of synthetic data?

**Comment by bigdaronlee163** [comment]
the method like MST，MWEM+PGM only be applied to discrete data?

**Comment by ryan112358** [comment]
@bigdaronlee163 great questions.  

1) All we require is that 0<= max(data.df[col]) < data.domain[col], which you'll see is true in your example above.

2) It's better to have smaller domains in general.  If you have one attribute that can take 10000 possible values, the code may work, but it's scalability and/or accuracy may suffer.  It's best to keep these small, even 100 is probably larger than it needs to be for the discretized numeric attributes in the adult dataset.  

3) Yes, all mechanisms that use Private-PGM expect discrete data, but it's an interesting open problem to develop approaches that can handle numeric data as well!
